# Generated by Django 5.1.3 on 2024-12-23 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('gid', models.IntegerField(primary_key=True, serialize=False)),
                ('p1_score', models.IntegerField(default=0)),
                ('p2_score', models.IntegerField(default=0)),
                ('winner', models.IntegerField(default=-1)),
                ('loser', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('games', models.ManyToManyField(blank=True, through='game.Game', to='game.player')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='p1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p1', to='game.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='p2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p2', to='game.player'),
        ),
    ]
